### ISSUE TITLE
README is out of sync with current application state

### ISSUE THREAD

**Issue by mpenning** [kincl/oncall#1]
Hi,

I'm interested in using this application where I work... I cloned the app and fired up a virtualenv (Python 2.7).  However, the `README` file says I should initialize the application like this...
- Edit `setttings.testing.cfg` and export them into a linux shell
- `python manage.py init_db`
- `python manage.py sync_ldap`
- `python manage.py runserver`

I ran into a few of issues... 
1.  The application seems to override everything in `settings.testing.cfg` in `main.py`; no matter where I define a database in `settings.testing.cfg` it always gets overrided by `main.py`.  I'm fine with that, but the README is misleading on this point.
2.  When I run the application with `python manage.py runserver`, the application URLs are pretty mixed up... the only way I can find a login page is by going to `http://localhost/api/vi/teams`, but if I click the "Oncall Calendar" hyperlink at the top left-hand side of the application, I get redirected to `http://localhost/` which generates a 404 error.
3.  I'm missing how to kickstart the application with a new administrative user.  Any thoughts?
4.  the `sync_ldap` option is commented out in `manage.py`; when I uncomment it and run `python manage.py sync_ldap`, I get the following traceback...

```
(py27_oncall)[mpenning@tsunami oncall]$ python manage.py sync_ldap
Traceback (most recent call last):
  File "manage.py", line 51, in <module>
    manager.run()
  File "/opt/virtual_env/py27_oncall/lib/python2.7/site-packages/flask_script/__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/opt/virtual_env/py27_oncall/lib/python2.7/site-packages/flask_script/__init__.py", line 383, in handle
    res = handle(*args, **config)
  File "/opt/virtual_env/py27_oncall/lib/python2.7/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "manage.py", line 29, in sync_ldap
    sync_users()
  File "/home/mpenning/oncall/oncall/ldap_helper.py", line 49, in sync_users
    current_app.db.session.commit()
  File "/opt/virtual_env/py27_oncall/lib/python2.7/site-packages/werkzeug/local.py", line 338, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'Flask' object has no attribute 'db'
(py27_oncall)[mpenning@tsunami oncall]$
```

Overall, thank you for publishing your work... I realize this is free code, and as such things could be in a state of flux (at least some of my GPL projects are).  Any assistance is appreciated.

Best Regards,
\mike

**Comment by kincl** [comment]
Hi Mike,

Glad you are interested! I am actually in the middle of a bit of a rewrite as I am restructuring oncall into a better flask app. Let me see what I can do over the next few days to finish cutting over and I will update the README to reflect the changes.

Thanks for the report!
